
<?php
    $curso = $dados[0];
?>

<section class="card card-body">
    <h1>Editar curso</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome: </label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $curso->nome?>">
                <label for="cargaHoraria">Carga horaria:</label>
                <input name="cargaHoraria" type="number" id="cargaHoraria" class="form-control mb-3" value="<?php echo $curso->cargaHoraria?>">
                <label for="descricao">Descrição: </label>
                <input name="descricao" type="text" id="descricao" class="form-control mb-3" value="<?php echo $curso->descricao?>">
                <label for="categoria">Categoria: </label>
                <select name="categoria" id="categoria" class="form-select mb-3">
                    <?php
                    foreach($categorias as $categoria){
                        if($curso->categoria_id == $categoria->id){
                            echo "
                            <option value='{$categoria->id}' selected>{$categoria->nome}</option>
                            ";
                        }
                        else{
                            echo "
                            <option value='{$categoria->id}'>{$categoria->nome}</option>
                            ";
                        }
                    }
                    ?>
                </select>
                <button class="btn btn-primary">Editar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>